"""Renders final report markdown to PDF using WeasyPrint and uploads to Supabase Storage."""

from __future__ import annotations

import os
import re
import tempfile
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv

load_dotenv()

# CSS template for PDF rendering
_PDF_CSS = """
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

@page {
    margin: 2cm 2.2cm;
    size: A4;

    @bottom-center {
        content: "Generated by Quorint — quorint.com";
        font-family: Inter, sans-serif;
        font-size: 9pt;
        color: #6b7280;
    }

    @bottom-right {
        content: "Page " counter(page) " of " counter(pages);
        font-family: Inter, sans-serif;
        font-size: 9pt;
        color: #6b7280;
    }
}

body {
    font-family: Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    font-size: 10.5pt;
    line-height: 1.6;
    color: #1f2937;
}

/* Logo placeholder */
.report-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    border-bottom: 2px solid #1a4a4a;
    padding-bottom: 12px;
    margin-bottom: 24px;
}

.report-logo {
    font-size: 20pt;
    font-weight: 700;
    color: #1a4a4a;
    letter-spacing: -0.5px;
}

.report-meta {
    font-size: 9pt;
    color: #6b7280;
    text-align: right;
}

/* Section headings */
h1 {
    font-size: 20pt;
    font-weight: 700;
    color: #1a4a4a;
    margin-top: 0;
    margin-bottom: 4px;
}

h2 {
    font-size: 14pt;
    font-weight: 600;
    color: #1a4a4a;
    border-bottom: 1px solid #d1fae5;
    padding-bottom: 6px;
    margin-top: 28px;
    margin-bottom: 14px;
    page-break-after: avoid;
}

h3 {
    font-size: 11.5pt;
    font-weight: 600;
    color: #1f2937;
    margin-top: 18px;
    margin-bottom: 8px;
    page-break-after: avoid;
}

h4 {
    font-size: 10.5pt;
    font-weight: 600;
    color: #374151;
    margin-top: 14px;
    margin-bottom: 6px;
}

/* Margin calculation box — most important number */
.margin-box {
    background: #ecfdf5;
    border: 2px solid #10b981;
    border-radius: 6px;
    padding: 12px 16px;
    margin: 16px 0;
}

.margin-box.tight {
    background: #fffbeb;
    border-color: #f59e0b;
}

.margin-box.not-viable {
    background: #fef2f2;
    border-color: #ef4444;
}

/* Tables */
table {
    width: 100%;
    border-collapse: collapse;
    margin: 12px 0;
    font-size: 10pt;
    page-break-inside: avoid;
}

th {
    background: #f0fdfa;
    color: #1a4a4a;
    font-weight: 600;
    padding: 8px 12px;
    text-align: left;
    border-bottom: 2px solid #1a4a4a;
}

td {
    padding: 7px 12px;
    border-bottom: 1px solid #e5e7eb;
}

tr:last-child td {
    border-bottom: none;
}

tr:nth-child(even) td {
    background: #f9fafb;
}

/* Buyer badges */
.badge-warm {
    display: inline-block;
    background: #d1fae5;
    color: #065f46;
    font-size: 8.5pt;
    font-weight: 600;
    padding: 2px 8px;
    border-radius: 9999px;
    margin-left: 6px;
}

.badge-cold {
    display: inline-block;
    background: #f3f4f6;
    color: #374151;
    font-size: 8.5pt;
    font-weight: 600;
    padding: 2px 8px;
    border-radius: 9999px;
    margin-left: 6px;
}

/* Blockquotes — used for working capital callout */
blockquote {
    border-left: 4px solid #1a4a4a;
    background: #f0fdfa;
    padding: 10px 16px;
    margin: 12px 0;
    font-style: italic;
    color: #065f46;
}

/* Risk flags */
.risk-high {
    background: #fef2f2;
    border-left: 4px solid #ef4444;
    padding: 10px 14px;
    margin: 10px 0;
    border-radius: 0 4px 4px 0;
}

.risk-medium {
    background: #fffbeb;
    border-left: 4px solid #f59e0b;
    padding: 10px 14px;
    margin: 10px 0;
    border-radius: 0 4px 4px 0;
}

/* Critical compliance marker */
.critical-marker {
    color: #ef4444;
    font-weight: 700;
}

/* Lists */
ul, ol {
    margin: 8px 0;
    padding-left: 20px;
}

li {
    margin-bottom: 4px;
}

/* Horizontal rule */
hr {
    border: none;
    border-top: 1px solid #e5e7eb;
    margin: 20px 0;
}

/* Code / email body */
pre, code {
    font-family: "Courier New", monospace;
    font-size: 9.5pt;
    background: #f9fafb;
    border: 1px solid #e5e7eb;
    border-radius: 4px;
    padding: 2px 5px;
}

pre {
    padding: 12px 16px;
    white-space: pre-wrap;
    word-wrap: break-word;
}

/* Page break helpers */
.page-break {
    page-break-before: always;
}

strong {
    font-weight: 600;
    color: #111827;
}

em {
    color: #6b7280;
    font-style: italic;
}

p {
    margin: 8px 0;
}
"""


def _markdown_to_html(markdown: str, report_id: str, title: str = "Quorint Report") -> str:
    """Convert markdown to styled HTML for PDF rendering."""
    try:
        import markdown as md_lib
        # Use Python-Markdown with extras
        html_body = md_lib.markdown(
            markdown,
            extensions=["tables", "fenced_code", "nl2br", "sane_lists"],
        )
    except ImportError:
        # Fallback: basic conversion if markdown library not installed
        html_body = _basic_markdown_to_html(markdown)

    # Apply semantic class to margin verdict boxes
    for verdict, css_class in [("VIABLE", "margin-box"), ("TIGHT", "margin-box tight"), ("NOT_VIABLE", "margin-box not-viable")]:
        html_body = html_body.replace(
            f"<strong>{verdict}</strong>",
            f'<span class="margin-verdict {css_class.split()[1] if " " in css_class else ""}">{verdict}</span>',
        )

    # Style buyer warm/cold badges
    html_body = re.sub(
        r"\[score:\s*(\d+)\]",
        lambda m: (
            f'<span class="badge-warm">score {m.group(1)}</span>'
            if int(m.group(1)) >= 70
            else f'<span class="badge-cold">score {m.group(1)}</span>'
        ),
        html_body,
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{title}</title>
    <style>
{_PDF_CSS}
    </style>
</head>
<body>
    <div class="report-header">
        <div class="report-logo">Quorint</div>
        <div class="report-meta">Report ID: {report_id[:8]}...</div>
    </div>
    {html_body}
</body>
</html>"""


def _basic_markdown_to_html(markdown: str) -> str:
    """Minimal markdown → HTML conversion (fallback if markdown library missing)."""
    lines = markdown.split("\n")
    html_lines = []
    in_table = False
    in_code = False

    for line in lines:
        # Code blocks
        if line.startswith("```"):
            if in_code:
                html_lines.append("</code></pre>")
                in_code = False
            else:
                html_lines.append("<pre><code>")
                in_code = True
            continue

        if in_code:
            html_lines.append(line)
            continue

        # Headings
        if line.startswith("#### "):
            html_lines.append(f"<h4>{_inline_md(line[5:])}</h4>")
        elif line.startswith("### "):
            html_lines.append(f"<h3>{_inline_md(line[4:])}</h3>")
        elif line.startswith("## "):
            html_lines.append(f"<h2>{_inline_md(line[3:])}</h2>")
        elif line.startswith("# "):
            html_lines.append(f"<h1>{_inline_md(line[2:])}</h1>")
        elif line.startswith("> "):
            html_lines.append(f"<blockquote>{_inline_md(line[2:])}</blockquote>")
        elif line.startswith("- ") or line.startswith("* "):
            html_lines.append(f"<li>{_inline_md(line[2:])}</li>")
        elif line.startswith("---"):
            html_lines.append("<hr>")
        elif line.strip() == "":
            html_lines.append("<br>")
        elif "|" in line and line.strip().startswith("|"):
            # Table row
            if not in_table:
                html_lines.append("<table>")
                in_table = True
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if all(re.match(r"[-:]+$", c) for c in cells if c):
                continue  # skip separator row
            row_html = "".join(f"<td>{_inline_md(c)}</td>" for c in cells)
            html_lines.append(f"<tr>{row_html}</tr>")
        else:
            if in_table:
                html_lines.append("</table>")
                in_table = False
            html_lines.append(f"<p>{_inline_md(line)}</p>")

    if in_table:
        html_lines.append("</table>")

    return "\n".join(html_lines)


def _inline_md(text: str) -> str:
    """Convert inline markdown (bold, italic, code) to HTML."""
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
    text = re.sub(r"`(.+?)`", r"<code>\1</code>", text)
    return text


def generate_pdf(report_markdown: str, report_id: str) -> str:
    """
    Convert report markdown to styled PDF, upload to Supabase Storage.
    Returns a signed URL valid for 24 hours.

    Falls back to writing to /tmp/{report_id}.pdf if Supabase upload fails.
    """
    # Convert markdown → HTML
    html = _markdown_to_html(report_markdown, report_id)

    # Generate PDF bytes using WeasyPrint
    try:
        from weasyprint import HTML, CSS
        pdf_bytes = HTML(string=html).write_pdf()
    except ImportError:
        raise RuntimeError("WeasyPrint not installed. Run: pip install weasyprint")
    except Exception as e:
        raise RuntimeError(f"WeasyPrint failed: {e}")

    # Write to temp file (also serves as local output for tests)
    tmp_path = f"/tmp/{report_id}.pdf"
    with open(tmp_path, "wb") as f:
        f.write(pdf_bytes)

    # Upload to Supabase Storage
    supabase_url = os.getenv("SUPABASE_URL")
    supabase_key = os.getenv("SUPABASE_SERVICE_ROLE_KEY")

    if not supabase_url or not supabase_key:
        print(f"[PDF] Supabase not configured — PDF saved to {tmp_path}")
        return tmp_path

    try:
        from supabase import create_client
        db = create_client(supabase_url, supabase_key)

        storage_path = f"{report_id}.pdf"
        bucket = "reports"

        # Ensure bucket exists (graceful if it already exists)
        try:
            db.storage.create_bucket(bucket, options={"public": False})
        except Exception:
            pass  # bucket already exists

        # Upload PDF bytes
        db.storage.from_(bucket).upload(
            path=storage_path,
            file=pdf_bytes,
            file_options={"content-type": "application/pdf"},
        )

        # Get signed URL valid for 24 hours
        signed = db.storage.from_(bucket).create_signed_url(storage_path, expires_in=86400)
        signed_url = signed.get("signedURL") or signed.get("signed_url") or signed.get("signedUrl")

        if signed_url:
            print(f"[PDF] Uploaded to Supabase Storage: {storage_path}")
            return signed_url

        # Fallback: return public URL
        public_url = db.storage.from_(bucket).get_public_url(storage_path)
        return public_url or tmp_path

    except Exception as e:
        print(f"[PDF] Supabase upload failed: {e} — returning local path {tmp_path}")
        return tmp_path


def generate_pdf_local(report_markdown: str, output_path: str) -> str:
    """Write PDF directly to output_path (for CLI test tool and test suite)."""
    html = _markdown_to_html(report_markdown, report_id=Path(output_path).stem)

    try:
        from weasyprint import HTML
        HTML(string=html).write_pdf(output_path)
        print(f"[PDF] Written to {output_path}")
        return output_path
    except ImportError:
        raise RuntimeError("WeasyPrint not installed. Run: pip install weasyprint")
    except Exception as e:
        raise RuntimeError(f"WeasyPrint PDF generation failed: {e}")
